host_mgr:
    port: 5000
    addr: 127.0.0.1
config_mgr: 5001
    port: 5001
    addr: 127.0.0.1
event_mgr:
    port: 5002
    addr: 127.0.0.1
monitoring_mgr:
    port: 5003
    addr: 127.0.0.1
logging_mgr:
    port: 5004
    addr: 127.0.0.1

